blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a Question (from .github repo)
    url: https://github.com/somespecialone/repo/discussions/new?category=q-a
    about: Ask a question about how to use pydantic using github discussions
